[package]
name = "rust-bevy-fourth"
version = "0.12.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
bevy_rapier3d = { version = "0.23", features = [ "simd-stable", "debug-render" ] }
lerp = "*"
rand = "*"
bevy_egui = "0.24"
#bevy-inspector-egui = "0.21"
bevy_asset_loader = "0.19"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
