[package]
name = "rust-bevy-fourth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_rapier3d = { version = "0.19.0", features = [ "simd-stable", "debug-render" ] }
lerp = "*" #"0.4"
rand = "*"
bevy_egui = "0.18"
bevy-inspector-egui = "0.16"
bevy-inspector-egui-rapier = { version = "0.9", features = ["rapier3d"] }